baseurl = "https://openpass.eclipse.org/"
DefaultContentLanguage = "en"
title = "OpenPASS"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = "UA-910670-30"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The rise of advanced driver assistance systems and partially automated driving functions leads to the need of virtual simulation to assess these systems and their effects."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["automotive", "systems", "engineering"]
  logo = "images/openpass/logo.png"
  styles = "css/styles.css"
  favicon = "images/openpass/favicon.ico"
  share_img = "images/openpass/logo.png"
# gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
  call_for_action_text = "Download"
  call_for_action_url = "https://git.eclipse.org/r/plugins/gitiles/simopenpass/simopenpass/"
  call_for_action_icon = "fa-download"
  call_for_action_classes = "btn btn-secondary btn-huge"
  featured_content_publish_target = "openpass"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
    name = "Target Objectives"
    url = "/target_objectives"
    weight = "1"
    
[[menu.main]]
    name = "Architecture"
    url = "/architecture"
    weight = "2"
    
[[menu.main]]
    name = "Platform Concept"
    url = "/architecture/#platform-concept"
    parent = "Architecture"
    weight = "1"
    
[[menu.main]]
    name = "Top-Level Architecture"
    url = "/architecture/#top-level-architecture"
    parent = "Architecture"
    weight = "2"   

[[menu.main]]
    name = "Simulation Process"
    url = "/architecture/#simulation-process-from-the-user-perspective"
    parent = "Architecture"
    weight = "3"
    
[[menu.main]]
    name = "Working Group"
    url = "#"
    weight = "3"
    
[[menu.main]]
    name = "Scope"
    url = "/about/#scope"
    parent = "Working Group"
    weight = "1"
    
[[menu.main]]
    name = "Timeline"
    url = "/about/#timeline"
    parent = "Working Group"
    weight = "2"
    
[[menu.main]]
    name = "Governance"
    url = "/about/#governance"
    parent = "Working Group"
    weight = "3"

[[menu.main]]
    name = "Members"
    url = "/about/#members"
    parent = "Working Group"
    weight = "4"

[[menu.main]]
    name = "Committees"
    url = "/about/#committees"
    parent = "Working Group"
    weight = "5"
    
[[menu.main]]
    name = "Resources"
    url = "/resources"
    weight = "4"
    
[[menu.main]]
    name = "Sim@openPASS"
    url = "/resources/#sim@openPASS"
    parent = "Resources"
    weight = "1"
    
[[menu.main]]
    name = "Installation"
    url = "/resources/#installation"
    parent = "Resources"
    weight = "2"
    
[[menu.main]]
    name = "Tutorial"
    url = "/resources/#tutorial"
    parent = "Resources"
    weight = "3"
    
[[menu.main]]
    name = "Documentation"
    url = "/resources/#documentation"
    parent = "Resources"
    weight = "4"
    
[[menu.main]]
    name = "Glossary"
    url = "/resources/#glossary"
    parent = "Resources"
    weight = "5"
    
[[menu.main]]
    name = "Report a bug"
    url = "/resources/#report-a-bug"
    parent = "Resources"
    weight = "6"
       
[[menu.main]]
    name = "Contact"
    url = "/about/contact"
    weight = "5"
